##:schema https://json.schemastore.org/any.json
#:schema https://raw.githubusercontent.com/air-verse/air/0a3f56961f682c08c2d012dbf828188b4e12e854/air.schema.json

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/main"
cmd = "go tool templ generate && go build -o ./tmp/main ./cmd/app"
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata", "sql"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "templ"]
include_file = []
kill_delay = 500
log = "build-errors.log"
poll = false
poll_interval = 500
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = true

[proxy]
enabled = true
proxy_port = 3000
app_port = 8080

[screen]
clear_on_rebuild = false
keep_scroll = true
