services:
    postgres:
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: fairsplit
        volumes:
            - db-data:/var/lib/postgresql/data

    app:
        build: .
        container_name: fairsplit
        restart: unless-stopped
        environment:
            ENV: production
            DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/fairsplit
            PORT: "8080"
            REVERSE_PROXY:

            CRYPT_KEY:
            GOOGLE_CLIENT_ID:
            GOOGLE_CLIENT_SECRET:
            GOOGLE_CALLBACK_URL:
        depends_on:
            - postgres

volumes:
    db-data:
