services:
    postgres:
        image: postgres:17
        # container_name: postgres
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: fairsplit
        volumes:
            - postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    app:
        build:
            context: .
        command: ["air"]
        environment:
            DATABASE_URL: postgres://postgres:secret@postgres:5432/fairsplit
            PORT: "8080"
        volumes:
            - ./:/app
        ports:
            - "8080:8080"
            - "3000:3000"
        depends_on:
            - postgres

    adminer:
        image: adminer:latest
        # container_name: adminer
        restart: unless-stopped
        ports:
            - 8081:8080
        environment:
            ADMINER_DESIGN: flat
            ADMINER_PLUGINS: edit-foreign edit-textarea enum-option json-column tables-filter config menu-links table-indexes-structure table-structure
        depends_on:
            - postgres
        links:
            - postgres:db

volumes:
    postgres:
