// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO
    session_participants (session_id, user_id)
VALUES
    ($1, $2)
`

type AddParticipantParams struct {
	SessionID uuid.UUID `json:"session_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.SessionID, arg.UserID)
	return err
}

const closeSession = `-- name: CloseSession :exec
UPDATE sessions
SET
    is_closed = TRUE
WHERE
    id = $1
`

func (q *Queries) CloseSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, closeSession, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO
    sessions (id, created_by_id, name)
VALUES
    ($1, $2, $3)
RETURNING
    id, created_by_id, name, is_closed, created_at, updated_at
`

type CreateSessionParams struct {
	ID          uuid.UUID `json:"id"`
	CreatedByID uuid.UUID `json:"created_by_id"`
	Name        string    `json:"name"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.ID, arg.CreatedByID, arg.Name)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.Name,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE
    id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT
    s.id, s.created_by_id, s.name, s.is_closed, s.created_at, s.updated_at,
    /* sql-formatter-disable */
    u.id, u.username, u.created_at, u.updated_at -- sql-formatter-disable
    /* sql-formatter-enable */
FROM
    sessions s
    JOIN users u ON u.id = s.created_by_id
WHERE
    s.id = $1
`

type GetSessionRow struct {
	ID          uuid.UUID          `json:"id"`
	CreatedByID uuid.UUID          `json:"created_by_id"`
	Name        string             `json:"name"`
	IsClosed    pgtype.Bool        `json:"is_closed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	User        User               `json:"user"`
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedByID,
		&i.Name,
		&i.IsClosed,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT
    id, created_by_id, name, is_closed, created_at, updated_at
FROM
    sessions
WHERE
    sessions.created_by_id = $1
`

func (q *Queries) ListSessionsForUser(ctx context.Context, createdByID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, createdByID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByID,
			&i.Name,
			&i.IsClosed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
